# Generated by Django 4.2.9 on 2024-02-04 19:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce_db_2', '0002_alter_products_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='categoryImage',
        ),
    ]
