# Generated by Django 4.2.9 on 2024-02-02 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('image', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=300)),
                ('rating', models.IntegerField(default=0)),
                ('price', models.IntegerField(default=0)),
                ('category', models.CharField(max_length=100)),
                ('categoryImage', models.CharField(max_length=200)),
            ],
        ),
    ]
