# Generated by Django 4.2.9 on 2024-02-02 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eCommerce', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='rating',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
